[package]
name = "kyber-pqc-sys"
version.workspace = true
include = [
    "build.rs",
    "src/**/*",
    "c/src/**/*.c",
    "c/src/**/*.h",
    "c/include/**/*.h",
    "c/vendor/**/*.c",
    "c/vendor/**/*.h",
]
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
description = "FFI bindings to the kyber-pqc native C core"
links = "kyber_pqc"
build = "build.rs"

[build-dependencies]
cc = "1.2"
