name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: cargo test
        run: cargo test --workspace --verbose

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
